### ISSUE TITLE
Transformers doesn't work with outFile: "some"

### ISSUE THREAD

**Issue by cevek** [cevek/ttypescript#29]

**Comment by SalvatorePreviti** [comment]
I did some investigation on this problem, it seems that there is no issue in ttypescript but the issue is in typescript itself. The problem is that when bundling to an AMD or a SystemJS module, typescript passes a Bundle node instead of a SourceFile node.

For example, changing the `before` transformer taking in consideration this behaviour executes the transformer correctly : [see here](https://github.com/SalvatorePreviti/ttypescript/blob/7396aade231b93440e7069f0f321de4351857502/packages/ttypescript/__tests__/transforms/before.ts)

There are two options here:
1) leaving it as it is and write this in the documentation
2) wrap the transformer in the plugin builder in such a way if we get a Bundle node we execute the transformer for every SourceFile in the Bundle node. This would potentially break existing transformers.

What is your opinion in this? I can work on the second if needed.

**Comment by cevek** [comment]
You're right, this problem is in the typescript. But another problem is that nobody who writes transformers do it right. So I think better way is add new option to plugin config something like `fixBundle: true` to fix this problem. 

ps: ts internally uses chainBundle: https://github.com/Microsoft/TypeScript/issues/28310
