### ISSUE TITLE
How to integrate with create react app?

### ISSUE THREAD

**Issue by Pita** [cevek/ttypescript#74]
Hello,

I love ttypescript, thank you! I'm currently trying to figure out how to integrate it into a project created with "create react app". I know that CRE uses webpack under the hood and that there are modules that let you rewire that webpack config. Could you provide an example of how to do it correctly?

**Comment by cevek** [comment]
Hello @Pita!
I think it's not ease to configure webpack config in the CRE, so try another tool https://github.com/nonara/ts-patch based on ttypescript, which patches installed typescript library inside node_modules. After applying this patch you don't need to configure your CRE, because your installed typescript would be act like ttypescript

**Comment by cevek** [comment]
@nonara is it possible right?

**Comment by nonara** [comment]
It should work, yes! ts-patch will apply the same logic directly to the typescript installation, so you shouldn't need to configure webpack.

@Pita try running this in your project dir: `npx ts-patch install --persist`

**Comment by w0nche0l** [comment]
Just wanted to put this here in case other people stumble upon this thread: 

From what I can tell, ts-patch will modify the typescript installation in your project, but the problem is that Create React App does NOT use typescript at all except for type checking. 

It uses babel for the actual compilation/emitting javascript, so ts-patch will not help you will getting custom transformers in create react app, and it seems like the only real solution is to rewrite the transformers entirely for babel (https://github.com/babel/babel/issues/9813) or stop using create react app's build scripts and switch to a ttsc based build.
